# Generated by Django 2.2.3 on 2022-05-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menssagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menssagem', models.TextField()),
                ('usuario', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSugestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_video', models.CharField(max_length=100)),
                ('usuario_video', models.CharField(max_length=15)),
            ],
        ),
    ]
