# Generated by Django 2.2.3 on 2022-05-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosugestao',
            name='link_video',
            field=models.CharField(max_length=100, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='videosugestao',
            name='usuario_video',
            field=models.CharField(max_length=15, verbose_name='usuario'),
        ),
    ]
