# Generated by Django 2.2.3 on 2022-05-06 00:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0002_auto_20220505_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='menssagens',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 5, 6, 0, 21, 15, 755378, tzinfo=utc)),
        ),
    ]
