# Generated by Django 2.2.3 on 2022-05-06 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0003_menssagens_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobreMim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobre', models.TextField()),
                ('projetos', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='menssagens',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
