# Generated by Django 2.2.3 on 2022-05-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0004_auto_20220505_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobremim',
            name='mostrar',
            field=models.BooleanField(default=False),
        ),
    ]
