# Generated by Django 2.2.3 on 2022-05-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0005_sobremim_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='menssagens',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
